[mypy]
python_version = 3.12
strict = True
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = False

plugins = pydantic.mypy

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-tests.*]
ignore_errors = True
